### ISSUE TITLE
Add floating controls

### ISSUE THREAD

**Issue by kellub** [anickle060193/easy_control#101]
It would be cool to have a widget-like control that could be separate from chrome (perhaps launched from the extension) that would show progress of media, media title, play/pause, forward, and back controls.

I know there are note-taking chrome extensions (think sticky-note) that allow widgets controlled by chrome, maybe it could be similar to those?

**Comment by kellub** [comment]
I guess the real reason I want this is a small way to see the name of the song ( I don't care so much about the actual controls ).

**Comment by anickle060193** [comment]
Closed in version 2.0.0
