### ISSUE TITLE
Can't blacklist twitch

### ISSUE THREAD

**Issue by kellub** [anickle060193/easy_control#103]
'twitch.tv' doesn't seem to actually blacklist twitch.

**Comment by anickle060193** [comment]
You should be able to disable the controller for Twitch from the options page.

**Comment by kellub** [comment]
That seems to have fixed it, sorta. But, when a new media is opened (with an existing twitch window open), twitch seems to reload it's media.

**Comment by anickle060193** [comment]
Closing as a result of major re-work for version 2.0.0. Please comment back if this is still an issue.
