### ISSUE TITLE
Keyboard Shortcut Issue

### ISSUE THREAD

**Issue by KCBunne** [anickle060193/easy_control#104]
Firstly, I would like to thank you for this extremely impressive extension. It honestly seems too good to be true that I can have complete control over my music with a few simple shortcuts no matter what I am doing or have open on my computer.
Something I thought I'd let you know about though is that the volume increase/decrease shortcut does not seem to work for Pandora.
Keep up the good work,
Kyle

**Comment by anickle060193** [comment]
Thanks for the support and I'm glad that you've benefited from the extension!

Regarding the volume control, unfortunately, only the generic media controller (the one that displays the playback speed controls) support volume control through the extension at this time. Issue #30 covers adding volume control too all the remaining controllers.
