### ISSUE TITLE
SPOTIFY IS BROKEN

### ISSUE THREAD

**Issue by kellub** [anickle060193/easy_control#105]
ADAM! SPOOOTERFLEA UPDATED ITS WEB CLIENT AND NOW NOTHING WORKDS. I BET THAT YOU COULD MAKE EVERYTHING BETTER THOUGH THIS TIME. (MAYBE VOLUME CONTROL SO JACOB WILL SHUT UP ABOUT IT?)

**Comment by anickle060193** [comment]
Duplicate of #106
