### ISSUE TITLE
ADD support Command/Mod4/Windows button in keyboard shortcuts

### ISSUE THREAD

**Issue by allanlaal** [anickle060193/easy_control#114]
keycode: 33

currently the default chrome keyboard shortcut manager does not capture the Command key for some reason

**Comment by anickle060193** [comment]
Is this in regard to the keyboard shortcuts popup that is opened when you click "Set Keyboard Shortcuts" from the options page for the extension? If that is the case, then this is, unfortunately, a limitation of Chrome where only certain keys are allowed for general Chrome keyboard shortcuts.

**Comment by allanlaal** [comment]
yes, I meant the Chrome keyboard shortcuts manager. Closing the issue then :(
