### ISSUE TITLE
Add play/pause control to media overlay

### ISSUE THREAD

**Issue by y1111** [anickle060193/easy_control#120]
the extension dont have a play/pause control and shortcut , i would like to have it , its the more simple and more used one . and it could have a Keyboard Shortcut for it - and by default the key can be: space bar . or can be : k . like on youtube
--

**Comment by y1111** [comment]
and control + shortcut for advance 10seg in videos like on youtube that has j and l key for reutrn10sec and adv10sec , (because other sites dont have it)

**Comment by anickle060193** [comment]
Created #121 for 10 second forward/backward control.
