### ISSUE TITLE
change playback speed of google play music player in chrome (windows)

### ISSUE THREAD

**Issue by Fierce-Ninja** [anickle060193/easy_control#122]
I installed your extension but for the life of me, can't find a way to change playback speed on google play music.  I tried on both the mini player and the main google play music player in chrome.  Could you please help me?

**Comment by anickle060193** [comment]
Unfortunately, playback speed control is not supported on Google Play Music. Playback speed control is only supported on sites that contain an HTML audio/video element. This includes Youtube, Hulu, Netflix, and most others that play a video.

**Comment by anickle060193** [comment]
So looking into this some more. It looks like Google Play Music does use audio elements for playing music. The media overlay controls should now display for Google Play Music to allow playback speed changes.
