### ISSUE TITLE
Provide an option to disable auto-pause

### ISSUE THREAD

**Issue by Luminus** [anickle060193/easy_control#127]
Can you please provide an option that allows a user to disable the auto-pause feature?

A lot of the time, I don't want the video auto-pausing and it's somewhat frustrating to have to go get the videos going again.

It's probably a useful feature for a lot of folks, which is why I'm asking for an option to be able to choose to disable it.

**Comment by anickle060193** [comment]
If you right-click the browser action icon for Easy Control in the top-right corner of the browser toolbar or in the browser options menu if you have the icon hidden, there is an option "Auto-Pause Enabled". You can use that to disable the auto-pause feature of the extension. There is also an "Auto-Pause Enabled for Tab" which you can use to disable the auto-pause feature for a specific tab.

**Comment by Luminus** [comment]
Awesome stuff. Thanks loads.
