### ISSUE TITLE
Video Speed Playback

### ISSUE THREAD

**Issue by kellub** [anickle060193/easy_control#29]
Hi, it's an issue that this extension doesn't support adjusting playback for HTML video. I suggest/demand that it uses the shortcut 's' for slow down, 'd' for speed up, and 'f' for fullscreen. I guess it doesn't have to use those, but shortcuts would definitely be helpful. It would also be very useful to see the current playback speed as an overlay on the video, but I imagine that's a lot of work ([this ](https://github.com/igrigorik/videospeed)extension handles it pretty well IMO).

Jacob recommended volume control for players (including music players) as well, but I don't care much about that.

**Comment by anickle060193** [comment]
Create separate issue for volume controls: #30.

**Comment by anickle060193** [comment]
List of feature details:
- Controls to change playback speed: much slower, slower, reset playback speed, faster, much faster.
- Only display controls when mouse over video
- Optionally display current playback speed when mouse **not** over video
