### ISSUE TITLE
Media Pauses Correctly

### ISSUE THREAD

**Issue by kellub** [anickle060193/easy_control#37]
So...this may be confusing.

Sometimes, when I'm watching YT videos, I'll be listening to a music video, and want to watch another video at the same time (muted, or quietly).
This isn't possible anymore with your extension.

I suggest adding a toast notification when you pause media saying 'Google Play Music paused', you could add an option to the notification saying to 'Resume Media', or something like that. I understand this may break your extension because you could theoretically have multiple media playing at once, but it'd be nice to overwrite the pause.

Even if you don't add that, it'd be cool to add a notification saying when you pause something.

**Comment by anickle060193** [comment]
Possibly add option to mark certain media to not be paused when other media starts.

**Comment by anickle060193** [comment]
Make auto-pause a configurable option.

**Comment by anickle060193** [comment]
Look into being able to disable auto-pause on a per-Tab basis.
