### ISSUE TITLE
YouTube: Video controls not displayed when first video is opened.

### ISSUE THREAD

**Issue by lannick** [anickle060193/easy_control#71]
When opening a video for the first time in a new tab the video controls are not displayed. This can happen in any new tab that opens youtube and loads a video for the first time.

**Comment by kellub** [comment]
Still exists. Can this be re-opened?

**Comment by kellub** [comment]
Still an issue. Seems like the very first time I visit YT, the controls don't appear.

I opened a video from the homepage to get this issue.
