### ISSUE TITLE
Open Spotify (or any media) links in that player if it already exists

### ISSUE THREAD

**Issue by kellub** [anickle060193/easy_control#84]
If I already have a spotify media player open, and attempt to open a link to a spotify album/song, I want the extension to open the media in the existing player (while maintaining my current playing song/queue).

Could add this to other music/media players as well, but I feel like they'd have to have some sort of 'queue' to work correctly. Spotify is definitely the priority though.

**Comment by anickle060193** [comment]
The current change made for this issue (mostly) operates how I think you wanted when you open Spotify-related links. It will close the current tab you're trying to open the content in and bring focus to the existing tab. For Spotify, most links related to browsing such as links to albums, playlists, etc. will open the relevant information as if you had clicked the album, playlist, etc. in the browsing window without affecting your currently playing music or queue. The one exception I've found is when you open a track link. This will overwrite your current queue and start playing the track as if you'd clicked the play button for the track.

**Comment by anickle060193** [comment]
When a track link is opened, after the album is opened, highlight the opened song.

**Comment by anickle060193** [comment]
Instead of sketchy injecting javascript commands as is being done now, look into injecting a javascript file that handles messages and send messages to page.
